
CATEGORY2CLASSNUM = {'AGE': 4, 'BMI': 4, 'SEX': 2, 'INJ': 2, 'SURG': 2, 'WOMAC': 4, 'KL': 4}
NUM_FEATURES = ['AGE','PAS','BMI','WOMAC','SF12','KOOSQoL']
CATEGORY_FEATURES = ['SEX', 'INJ', 'INJ', 'SIDE','KL']
SIDE_FEATURES = ['KL','WOMAC','INJ','SURG', 'KL_Prob','JSW','IMG']
PREDICTED_FEATURE=['KL','SF12','WOMAC']
MAX_SF12 = 69.59
MIN_SF12 = 8.81
MAX_MIN_SF12 = MAX_SF12 - MIN_SF12